# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select -verify-machineinstrs %s -verify-machineinstrs -o - | FileCheck %s

---
name:              vextract_vbcst_8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextract_vbcst_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: [[VEXTRACT_16_vec_extract_imm_vaddSign1_:%[0-9]+]]:er = VEXTRACT_16_vec_extract_imm_vaddSign1 [[VLD_x_idx_imm_pseudo]], 0, implicit $vaddsign1
    ; CHECK-NEXT: [[VBCST_16_:%[0-9]+]]:vec512 = VBCST_16 [[VEXTRACT_16_vec_extract_imm_vaddSign1_]]
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[VBCST_16_]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_LOAD %ptr(p0) :: (load (<32 x s16>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %6:gprregbank(s32) = G_ASSERT_SEXT %5, 16
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %6(s32)
    PseudoRET implicit $lr, implicit %7(<32 x s16>)
...

---
name:              vextract_vbcst_16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextract_vbcst_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: [[VEXTRACT_16_vec_extract_imm_vaddSign1_:%[0-9]+]]:er = VEXTRACT_16_vec_extract_imm_vaddSign1 [[VLD_x_idx_imm_pseudo]], 0, implicit $vaddsign1
    ; CHECK-NEXT: [[VBCST_16_:%[0-9]+]]:vec512 = VBCST_16 [[VEXTRACT_16_vec_extract_imm_vaddSign1_]]
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[VBCST_16_]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_LOAD %ptr(p0) :: (load (<32 x s16>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %6:gprregbank(s32) = G_ASSERT_SEXT %5, 16
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %6(s32)
    PseudoRET implicit $lr, implicit %7(<32 x s16>)
...

---
name:              vextract_vbcst_32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextract_vbcst_32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCSTSHFL_32_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_32 [[VLD_x_idx_imm_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_32_]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %3(s32)
    %6:gprregbank(<2 x s16>) = G_BITCAST %5(s32)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast32.bf512), %6(<2 x s16>)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    PseudoRET implicit $lr, implicit %8(<16 x s32>)
...


# The 
# %371:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %211(s32)
# %375:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %371(<16 x s32>), %371(<16 x s32>), %37(s32)

---
name:              vextract_vbcst_64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextract_vbcst_64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCSTSHFL_64_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_64 [[VLD_x_idx_imm_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_64_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_LOAD %0(p0) :: (load (<16 x s32>))
    %5:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %4(<16 x s32>), %3(s32)
    %6:gprregbank(<4 x s16>) = G_BITCAST %5(<2 x s32>)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast64.bf512), %6(<4 x s16>)
    PseudoRET implicit $lr, implicit %7(<32 x s16>)
...

---
name:              vextract_vbcst_128
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextract_vbcst_128
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCST_128_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_128_vec_extract_broadcast_imm [[VLD_x_idx_imm_pseudo]], 0
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[VEXTBCST_128_vec_extract_broadcast_imm]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_LOAD %0(p0) :: (load (<16 x s32>))
    %5:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vextract.broadcast128.I512), %4(<16 x s32>), %3(s32)
    PseudoRET implicit $lr, implicit %10(<16 x s32>)
...


