; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

; ModuleID = '/scratch/peano-tests/VITIS_AIE_QOR_MLLIB/mllib_gen-ir_peano/L1/regression/misc/AvgPool2D_0/Work/aie/0_0/Release/AvgPool2D_0.bc'
source_filename = "Work/aie/0_0/src/0_0.cc"
target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p-none-unknown-elf"

$_Z9avgpool2dILh1EaQsr5mllib5utilsE11is_one_of_vIT0_ah8bfloat167float16EEvPS0_S3_R25avgpool2d_internal_paramsIS0_E = comdat any

; Function Attrs: mustprogress noinline
define weak_odr dso_local void @_Z9avgpool2dILh1EaQsr5mllib5utilsE11is_one_of_vIT0_ah8bfloat167float16EEvPS0_S3_R25avgpool2d_internal_paramsIS0_E(ptr noalias %ifm_ptr, ptr noalias %ofm_ptr, ptr nonnull align 64 dereferenceable(64) %avgpool2d_params) local_unnamed_addr #0 comdat {
entry:
  %div_factor = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 46
  %0 = load i16, ptr %div_factor, align 2, !tbaa !4
  %splat.splatinsert.i.i.i.i.i = insertelement <32 x i16> poison, i16 %0, i64 0
  %splat.splat.i.i.i.i.i = shufflevector <32 x i16> %splat.splatinsert.i.i.i.i.i, <32 x i16> poison, <32 x i32> zeroinitializer
  %1 = bitcast <32 x i16> %splat.splat.i.i.i.i.i to <16 x i32>
  %2 = load i8, ptr %avgpool2d_params, align 64, !tbaa !10
  %conv = zext i8 %2 to i16
  %sub = add nsw i16 %conv, -2
  %mul = mul i16 %sub, %0
  %splat.splatinsert.i.i.i.i.i213 = insertelement <32 x i16> poison, i16 %mul, i64 0
  %splat.splat.i.i.i.i.i214 = shufflevector <32 x i16> %splat.splatinsert.i.i.i.i.i213, <32 x i16> poison, <32 x i32> zeroinitializer
  %3 = bitcast <32 x i16> %splat.splat.i.i.i.i.i214 to <16 x i32>
  %outer_loop_count = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 4
  %4 = load i16, ptr %outer_loop_count, align 4, !tbaa !11
  %conv4 = zext i16 %4 to i32
  %5 = icmp ugt i16 %4, 2
  tail call void @llvm.assume(i1 %5)
  %inc_Ky = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 28
  %6 = load i16, ptr %inc_Ky, align 4, !tbaa !12
  %idx.ext.i = sext i16 %6 to i20
  %shfl_0 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 40
  %7 = load i8, ptr %shfl_0, align 8, !tbaa !13
  %conv22 = sext i8 %7 to i32
  %shfl_1 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 41
  %8 = load i8, ptr %shfl_1, align 1, !tbaa !14
  %conv27 = sext i8 %8 to i32
  %shft_0 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 32
  %9 = load i8, ptr %shft_0, align 32, !tbaa !15
  %conv30 = sext i8 %9 to i32
  %cmp.i = icmp ult i8 %9, 65
  %shft_1 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 33
  %10 = load i8, ptr %shft_1, align 1, !tbaa !16
  %conv32 = sext i8 %10 to i32
  %cmp.i230 = icmp ult i8 %10, 65
  %shft_2 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 34
  %11 = load i8, ptr %shft_2, align 2, !tbaa !17
  %conv34 = sext i8 %11 to i32
  %cmp.i245 = icmp ult i8 %11, 65
  %shuffle.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i32> %1, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %12 = bitcast <32 x i32> %shuffle.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x i16>
  %shuffle.i.i.i.i.i20.i.i.i.i.i.i.i.i.i.i.i.i.i271 = shufflevector <16 x i32> %3, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %13 = bitcast <32 x i32> %shuffle.i.i.i.i.i20.i.i.i.i.i.i.i.i.i.i.i.i.i271 to <64 x i16>
  %inc_A_0 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 30
  %14 = load i16, ptr %inc_A_0, align 2, !tbaa !18
  %idx.ext.i312 = sext i16 %14 to i20
  %div_shift = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 48
  %15 = load i8, ptr %div_shift, align 16, !tbaa !19
  %conv144 = zext i8 %15 to i32
  %iterator_incr2 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 24
  %16 = load i32, ptr %iterator_incr2, align 8, !tbaa !20
  %iterator_wrap0 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 16
  %17 = load i32, ptr %iterator_wrap0, align 16, !tbaa !21
  %iterator_incr0 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 8
  %18 = load i32, ptr %iterator_incr0, align 8, !tbaa !22
  %iterator_wrap1 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 20
  %19 = load i32, ptr %iterator_wrap1, align 4, !tbaa !23
  %iterator_incr1 = getelementptr inbounds nuw i8, ptr %avgpool2d_params, i20 12
  %20 = load i32, ptr %iterator_incr1, align 4, !tbaa !24
  %21 = trunc i32 %16 to i20
  %22 = trunc i32 %18 to i20
  %23 = trunc i32 %20 to i20
  %24 = trunc i32 %17 to i20
  %25 = trunc i32 %19 to i20
  tail call void @llvm.assume(i1 %cmp.i)
  tail call void @llvm.assume(i1 %cmp.i230)
  tail call void @llvm.assume(i1 %cmp.i245)
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body, %entry
  %j.0694 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %output_ptr.0.in693 = phi ptr [ %ofm_ptr, %entry ], [ %add.ptr.i521, %for.body ]
  %input_ptr.0.in692 = phi ptr [ %ifm_ptr, %entry ], [ %139, %for.body ]
  %iterator_cnt0.0691 = phi i32 [ 0, %entry ], [ %136, %for.body ]
  %iterator_cnt1.0690 = phi i32 [ 0, %entry ], [ %138, %for.body ]
  %input_buff_2.sroa.0.0689 = phi <16 x i32> [ undef, %entry ], [ %shuffle1.i.i.i.i.i425, %for.body ]
  %output_ptr.0695 = addrspacecast ptr %output_ptr.0.in693 to ptr addrspace(5)
  %input_ptr.0 = addrspacecast ptr %input_ptr.0.in692 to ptr addrspace(5)
  %26 = load <8 x i32>, ptr addrspace(5) %input_ptr.0, align 32, !tbaa !25, !noalias !26
  %add.ptr.i = getelementptr inbounds nuw i8, ptr %input_ptr.0.in692, i20 32
  %add.ptr.ascast.i = addrspacecast ptr %add.ptr.i to ptr addrspace(5)
  %27 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i, align 32, !tbaa !25, !noalias !33
  %shuffle2.i.i.i.i.i = shufflevector <8 x i32> %26, <8 x i32> %27, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i216 = getelementptr inbounds nuw i8, ptr %input_ptr.0.in692, i20 64
  %add.ptr.ascast.i217 = addrspacecast ptr %add.ptr.i216 to ptr addrspace(5)
  %28 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i217, align 32, !tbaa !25, !noalias !40
  %add.ptr.i220 = getelementptr inbounds nuw i8, ptr %input_ptr.0.in692, i20 96
  %add.ptr.ascast.i221 = addrspacecast ptr %add.ptr.i220 to ptr addrspace(5)
  %29 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i221, align 32, !tbaa !25, !noalias !47
  %shuffle2.i.i.i.i.i223 = shufflevector <8 x i32> %28, <8 x i32> %29, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i224 = getelementptr inbounds nuw i8, ptr %input_ptr.0.in692, i20 128
  %add.ptr.ascast.i225 = addrspacecast ptr %add.ptr.i224 to ptr addrspace(5)
  %30 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i225, align 32, !tbaa !25, !noalias !54
  %shuffle.i.i.i.i.i226 = shufflevector <8 x i32> %30, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i227 = shufflevector <16 x i32> %shuffle.i.i.i.i.i226, <16 x i32> %input_buff_2.sroa.0.0689, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i228 = getelementptr inbounds i8, ptr %add.ptr.i224, i20 %idx.ext.i
  %add.ptr.ascast.i229 = addrspacecast ptr %add.ptr.i228 to ptr addrspace(5)
  %31 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %shuffle2.i.i.i.i.i, <16 x i32> %shuffle2.i.i.i.i.i223, i32 range(i32 -128, 128) %conv22)
  %32 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %shuffle2.i.i.i.i.i, <16 x i32> %shuffle2.i.i.i.i.i223, i32 range(i32 -128, 128) %conv27)
  %33 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %32, <16 x i32> %shuffle2.i.i.i.i.i223, i32 0, i32 %conv30)
  %34 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %31, <16 x i32> %shuffle1.i.i.i.i.i227, i32 0, i32 %conv32)
  %35 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %34, <16 x i32> %shuffle2.i.i.i.i.i223, i32 0, i32 %conv34)
  %shuffle.i.i.i.i.i.i = shufflevector <16 x i32> %31, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %36 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i to <32 x i8>
  %37 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %36, i32 1)
  %38 = bitcast <32 x i16> %37 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i32> %38, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %39 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mul.conf(<32 x i32> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i, <64 x i16> %12, i32 568)
  %shuffle.i.i.i.i.i.i260 = shufflevector <16 x i32> %33, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %40 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i260 to <32 x i8>
  %41 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %40, i32 1)
  %42 = bitcast <32 x i16> %41 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i263 = shufflevector <32 x i64> %39, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i32> %42, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %43 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i, <64 x i16> %12, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i263, i32 568)
  %shuffle.i.i.i.i.i.i265 = shufflevector <16 x i32> %35, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %44 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i265 to <32 x i8>
  %45 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %44, i32 1)
  %46 = bitcast <32 x i16> %45 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i269 = shufflevector <32 x i64> %43, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i270 = shufflevector <16 x i32> %46, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %47 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i270, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i269, i32 568)
  %shuffle1.i.i.i.i.i.i = shufflevector <16 x i32> %31, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %48 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i to <32 x i8>
  %49 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %48, i32 1)
  %50 = bitcast <32 x i16> %49 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i275 = shufflevector <16 x i32> %50, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %51 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mul.conf(<32 x i32> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i275, <64 x i16> %12, i32 568)
  %shuffle1.i.i.i.i.i.i278 = shufflevector <16 x i32> %33, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %52 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i278 to <32 x i8>
  %53 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %52, i32 1)
  %54 = bitcast <32 x i16> %53 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i282 = shufflevector <32 x i64> %51, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i283 = shufflevector <16 x i32> %54, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %55 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i283, <64 x i16> %12, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i282, i32 568)
  %shuffle1.i.i.i.i.i.i286 = shufflevector <16 x i32> %35, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %56 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i286 to <32 x i8>
  %57 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %56, i32 1)
  %58 = bitcast <32 x i16> %57 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i290 = shufflevector <32 x i64> %55, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i291 = shufflevector <16 x i32> %58, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %59 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i291, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i290, i32 568)
  %60 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i229, align 32, !tbaa !25, !noalias !61
  %add.ptr.i296 = getelementptr inbounds nuw i8, ptr %add.ptr.i228, i20 32
  %add.ptr.ascast.i297 = addrspacecast ptr %add.ptr.i296 to ptr addrspace(5)
  %61 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i297, align 32, !tbaa !25, !noalias !68
  %shuffle2.i.i.i.i.i299 = shufflevector <8 x i32> %60, <8 x i32> %61, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i300 = getelementptr inbounds nuw i8, ptr %add.ptr.i228, i20 64
  %add.ptr.ascast.i301 = addrspacecast ptr %add.ptr.i300 to ptr addrspace(5)
  %62 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i301, align 32, !tbaa !25, !noalias !75
  %add.ptr.i304 = getelementptr inbounds nuw i8, ptr %add.ptr.i228, i20 96
  %add.ptr.ascast.i305 = addrspacecast ptr %add.ptr.i304 to ptr addrspace(5)
  %63 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i305, align 32, !tbaa !25, !noalias !82
  %shuffle2.i.i.i.i.i307 = shufflevector <8 x i32> %62, <8 x i32> %63, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i308 = getelementptr inbounds nuw i8, ptr %add.ptr.i228, i20 128
  %add.ptr.ascast.i309 = addrspacecast ptr %add.ptr.i308 to ptr addrspace(5)
  %64 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i309, align 32, !tbaa !25, !noalias !89
  %shuffle.i.i.i.i.i310 = shufflevector <8 x i32> %64, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i311 = shufflevector <16 x i32> %shuffle.i.i.i.i.i310, <16 x i32> %shuffle1.i.i.i.i.i227, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i313 = getelementptr inbounds i8, ptr %add.ptr.i308, i20 %idx.ext.i312
  %add.ptr.ascast.i314 = addrspacecast ptr %add.ptr.i313 to ptr addrspace(5)
  %65 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %shuffle2.i.i.i.i.i299, <16 x i32> %shuffle2.i.i.i.i.i307, i32 range(i32 -128, 128) %conv22)
  %66 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %shuffle2.i.i.i.i.i299, <16 x i32> %shuffle2.i.i.i.i.i307, i32 range(i32 -128, 128) %conv27)
  %67 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %66, <16 x i32> %shuffle2.i.i.i.i.i307, i32 0, i32 %conv30)
  %68 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %65, <16 x i32> %shuffle1.i.i.i.i.i311, i32 0, i32 %conv32)
  %69 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %68, <16 x i32> %shuffle2.i.i.i.i.i307, i32 0, i32 %conv34)
  %shuffle.i.i.i.i.i.i360 = shufflevector <16 x i32> %65, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %70 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i360 to <32 x i8>
  %71 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %70, i32 1)
  %72 = bitcast <32 x i16> %71 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i364 = shufflevector <32 x i64> %47, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i365 = shufflevector <16 x i32> %72, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %73 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i365, <64 x i16> %12, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i364, i32 568)
  %shuffle.i.i.i.i.i.i368 = shufflevector <16 x i32> %67, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %74 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i368 to <32 x i8>
  %75 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %74, i32 1)
  %76 = bitcast <32 x i16> %75 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i372 = shufflevector <32 x i64> %73, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i373 = shufflevector <16 x i32> %76, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %77 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i373, <64 x i16> %12, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i372, i32 568)
  %shuffle.i.i.i.i.i.i376 = shufflevector <16 x i32> %69, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %78 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i376 to <32 x i8>
  %79 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %78, i32 1)
  %80 = bitcast <32 x i16> %79 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i380 = shufflevector <32 x i64> %77, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i381 = shufflevector <16 x i32> %80, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %81 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i381, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i380, i32 568)
  %shuffle1.i.i.i.i.i.i384 = shufflevector <16 x i32> %65, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %82 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i384 to <32 x i8>
  %83 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %82, i32 1)
  %84 = bitcast <32 x i16> %83 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i388 = shufflevector <32 x i64> %59, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i389 = shufflevector <16 x i32> %84, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %85 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i389, <64 x i16> %12, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i388, i32 568)
  %shuffle1.i.i.i.i.i.i392 = shufflevector <16 x i32> %67, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %86 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i392 to <32 x i8>
  %87 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %86, i32 1)
  %88 = bitcast <32 x i16> %87 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i396 = shufflevector <32 x i64> %85, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i397 = shufflevector <16 x i32> %88, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %89 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i397, <64 x i16> %12, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i396, i32 568)
  %shuffle1.i.i.i.i.i.i400 = shufflevector <16 x i32> %69, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %90 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i400 to <32 x i8>
  %91 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %90, i32 1)
  %92 = bitcast <32 x i16> %91 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i404 = shufflevector <32 x i64> %89, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i405 = shufflevector <16 x i32> %92, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %93 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i405, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i404, i32 568)
  %94 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i314, align 32, !tbaa !25, !noalias !96
  %add.ptr.i410 = getelementptr inbounds nuw i8, ptr %add.ptr.i313, i20 32
  %add.ptr.ascast.i411 = addrspacecast ptr %add.ptr.i410 to ptr addrspace(5)
  %95 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i411, align 32, !tbaa !25, !noalias !103
  %shuffle2.i.i.i.i.i413 = shufflevector <8 x i32> %94, <8 x i32> %95, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i414 = getelementptr inbounds nuw i8, ptr %add.ptr.i313, i20 64
  %add.ptr.ascast.i415 = addrspacecast ptr %add.ptr.i414 to ptr addrspace(5)
  %96 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i415, align 32, !tbaa !25, !noalias !110
  %add.ptr.i418 = getelementptr inbounds nuw i8, ptr %add.ptr.i313, i20 96
  %add.ptr.ascast.i419 = addrspacecast ptr %add.ptr.i418 to ptr addrspace(5)
  %97 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i419, align 32, !tbaa !25, !noalias !117
  %shuffle2.i.i.i.i.i421 = shufflevector <8 x i32> %96, <8 x i32> %97, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i422 = getelementptr inbounds nuw i8, ptr %add.ptr.i313, i20 128
  %add.ptr.ascast.i423 = addrspacecast ptr %add.ptr.i422 to ptr addrspace(5)
  %98 = load <8 x i32>, ptr addrspace(5) %add.ptr.ascast.i423, align 32, !tbaa !25, !noalias !124
  %shuffle.i.i.i.i.i424 = shufflevector <8 x i32> %98, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i425 = shufflevector <16 x i32> %shuffle.i.i.i.i.i424, <16 x i32> %shuffle1.i.i.i.i.i311, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %99 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %shuffle2.i.i.i.i.i413, <16 x i32> %shuffle2.i.i.i.i.i421, i32 range(i32 -128, 128) %conv22)
  %100 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %shuffle2.i.i.i.i.i413, <16 x i32> %shuffle2.i.i.i.i.i421, i32 range(i32 -128, 128) %conv27)
  %101 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %100, <16 x i32> %shuffle2.i.i.i.i.i421, i32 0, i32 %conv30)
  %102 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %99, <16 x i32> %shuffle1.i.i.i.i.i425, i32 0, i32 %conv32)
  %103 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %102, <16 x i32> %shuffle2.i.i.i.i.i421, i32 0, i32 %conv34)
  %shuffle.i.i.i.i.i.i471 = shufflevector <16 x i32> %99, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %104 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i471 to <32 x i8>
  %105 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %104, i32 1)
  %106 = bitcast <32 x i16> %105 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i475 = shufflevector <32 x i64> %81, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i476 = shufflevector <16 x i32> %106, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %107 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i476, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i475, i32 568)
  %shuffle.i.i.i.i.i.i479 = shufflevector <16 x i32> %101, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %108 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i479 to <32 x i8>
  %109 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %108, i32 1)
  %110 = bitcast <32 x i16> %109 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i483 = shufflevector <32 x i64> %107, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i484 = shufflevector <16 x i32> %110, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %111 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i484, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i483, i32 568)
  %shuffle.i.i.i.i.i.i487 = shufflevector <16 x i32> %103, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %112 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i487 to <32 x i8>
  %113 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %112, i32 1)
  %114 = bitcast <32 x i16> %113 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i491 = shufflevector <32 x i64> %111, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i492 = shufflevector <16 x i32> %114, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %115 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i492, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i491, i32 568)
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i494 = shufflevector <32 x i64> %115, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shuffle1.i.i.i.i.i.i495 = shufflevector <16 x i32> %99, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %116 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i495 to <32 x i8>
  %117 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %116, i32 1)
  %118 = bitcast <32 x i16> %117 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i499 = shufflevector <32 x i64> %93, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i500 = shufflevector <16 x i32> %118, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %119 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i500, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i499, i32 568)
  %shuffle1.i.i.i.i.i.i503 = shufflevector <16 x i32> %101, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %120 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i503 to <32 x i8>
  %121 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %120, i32 1)
  %122 = bitcast <32 x i16> %121 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i507 = shufflevector <32 x i64> %119, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i508 = shufflevector <16 x i32> %122, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %123 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i508, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i507, i32 568)
  %shuffle1.i.i.i.i.i.i511 = shufflevector <16 x i32> %103, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %124 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i511 to <32 x i8>
  %125 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %124, i32 1)
  %126 = bitcast <32 x i16> %125 to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i515 = shufflevector <32 x i64> %123, <32 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i516 = shufflevector <16 x i32> %126, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %127 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i.i.i516, <64 x i16> %13, <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i515, i32 568)
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i518 = shufflevector <32 x i64> %127, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %128 = bitcast <16 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i494 to <32 x i32>
  %129 = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> %128, i32 %conv144, i32 range(i32 0, 2) 1)
  store <32 x i8> %129, ptr addrspace(5) %output_ptr.0695, align 32, !tbaa !25
  %add.ptr.i519 = getelementptr inbounds nuw i8, ptr %output_ptr.0.in693, i20 32
  %add.ptr.ascast.i520 = addrspacecast ptr %add.ptr.i519 to ptr addrspace(5)
  %130 = bitcast <16 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i518 to <32 x i32>
  %131 = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> %130, i32 %conv144, i32 range(i32 0, 2) 1)
  store <32 x i8> %131, ptr addrspace(5) %add.ptr.ascast.i520, align 32, !tbaa !25
  %add.ptr.i521 = getelementptr inbounds nuw i8, ptr %output_ptr.0.in693, i20 64
  %132 = trunc nuw i32 %iterator_cnt0.0691 to i20
  %133 = trunc nuw i32 %iterator_cnt1.0690 to i20
  %134 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr nonnull %add.ptr.i422, i20 %21, i20 %22, i20 %23, i20 %24, i20 %132, i20 %25, i20 %133)
  %135 = extractvalue { ptr, i20, i20 } %134, 1
  %136 = zext i20 %135 to i32
  %137 = extractvalue { ptr, i20, i20 } %134, 2
  %138 = zext i20 %137 to i32
  %139 = extractvalue { ptr, i20, i20 } %134, 0
  %inc = add nuw nsw i32 %j.0694, 1
  %exitcond.not = icmp eq i32 %inc, %conv4
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !131
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare void @llvm.assume(i1 noundef) #1

; Function Attrs: nounwind willreturn memory(none)
declare <16 x i32> @llvm.aie2p.vshuffle(<16 x i32>, <16 x i32>, i32) #2

; Function Attrs: nounwind willreturn memory(none)
declare <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32>, <16 x i32>, i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mul.conf(<32 x i32>, <64 x i16>, i32) #3

; Function Attrs: nounwind willreturn memory(none)
declare <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8>, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32>, <64 x i16>, <32 x i64>, i32) #3

; Function Attrs: nounwind willreturn memory(inaccessiblemem: read)
declare <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32>, i32, i32) #4

; Function Attrs: nounwind willreturn memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #2

attributes #0 = { mustprogress noinline "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #2 = { nounwind willreturn memory(none) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #4 = { nounwind willreturn memory(inaccessiblemem: read) }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 20.0.0git (/scratch/work/clang c9c710446ecbf2938aa5fc31019abd6827e2335a)"}
!4 = !{!5, !8, i64 46}
!5 = !{!"_ZTS25avgpool2d_internal_paramsIaE", !6, i64 0, !6, i64 1, !6, i64 2, !8, i64 4, !9, i64 8, !9, i64 12, !9, i64 16, !9, i64 20, !9, i64 24, !8, i64 28, !8, i64 30, !6, i64 32, !6, i64 33, !6, i64 34, !6, i64 35, !6, i64 36, !6, i64 37, !6, i64 38, !6, i64 39, !6, i64 40, !6, i64 41, !8, i64 42, !6, i64 44, !8, i64 46, !6, i64 48}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C++ TBAA"}
!8 = !{!"short", !6, i64 0}
!9 = !{!"int", !6, i64 0}
!10 = !{!5, !6, i64 0}
!11 = !{!5, !8, i64 4}
!12 = !{!5, !8, i64 28}
!13 = !{!5, !6, i64 40}
!14 = !{!5, !6, i64 41}
!15 = !{!5, !6, i64 32}
!16 = !{!5, !6, i64 33}
!17 = !{!5, !6, i64 34}
!18 = !{!5, !8, i64 30}
!19 = !{!5, !6, i64 48}
!20 = !{!5, !9, i64 24}
!21 = !{!5, !9, i64 16}
!22 = !{!5, !9, i64 8}
!23 = !{!5, !9, i64 20}
!24 = !{!5, !9, i64 12}
!25 = !{!6, !6, i64 0}
!26 = !{!27, !29, !31}
!27 = distinct !{!27, !28, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!28 = distinct !{!28, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!29 = distinct !{!29, !30, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!30 = distinct !{!30, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!31 = distinct !{!31, !32, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!32 = distinct !{!32, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!33 = !{!34, !36, !38}
!34 = distinct !{!34, !35, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!35 = distinct !{!35, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!36 = distinct !{!36, !37, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!37 = distinct !{!37, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!38 = distinct !{!38, !39, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!39 = distinct !{!39, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!40 = !{!41, !43, !45}
!41 = distinct !{!41, !42, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!42 = distinct !{!42, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!43 = distinct !{!43, !44, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!44 = distinct !{!44, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!45 = distinct !{!45, !46, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!46 = distinct !{!46, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!47 = !{!48, !50, !52}
!48 = distinct !{!48, !49, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!49 = distinct !{!49, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!50 = distinct !{!50, !51, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!51 = distinct !{!51, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!52 = distinct !{!52, !53, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!53 = distinct !{!53, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!54 = !{!55, !57, !59}
!55 = distinct !{!55, !56, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!56 = distinct !{!56, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!57 = distinct !{!57, !58, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!58 = distinct !{!58, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!59 = distinct !{!59, !60, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!60 = distinct !{!60, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!61 = !{!62, !64, !66}
!62 = distinct !{!62, !63, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!63 = distinct !{!63, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!64 = distinct !{!64, !65, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!65 = distinct !{!65, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!66 = distinct !{!66, !67, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!67 = distinct !{!67, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!68 = !{!69, !71, !73}
!69 = distinct !{!69, !70, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!70 = distinct !{!70, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!71 = distinct !{!71, !72, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!72 = distinct !{!72, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!73 = distinct !{!73, !74, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!74 = distinct !{!74, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!75 = !{!76, !78, !80}
!76 = distinct !{!76, !77, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!77 = distinct !{!77, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!78 = distinct !{!78, !79, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!79 = distinct !{!79, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!80 = distinct !{!80, !81, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!81 = distinct !{!81, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!82 = !{!83, !85, !87}
!83 = distinct !{!83, !84, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!84 = distinct !{!84, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!85 = distinct !{!85, !86, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!86 = distinct !{!86, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!87 = distinct !{!87, !88, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!88 = distinct !{!88, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!89 = !{!90, !92, !94}
!90 = distinct !{!90, !91, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!91 = distinct !{!91, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!92 = distinct !{!92, !93, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!93 = distinct !{!93, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!94 = distinct !{!94, !95, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!95 = distinct !{!95, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!96 = !{!97, !99, !101}
!97 = distinct !{!97, !98, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!98 = distinct !{!98, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!99 = distinct !{!99, !100, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!100 = distinct !{!100, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!101 = distinct !{!101, !102, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!102 = distinct !{!102, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!103 = !{!104, !106, !108}
!104 = distinct !{!104, !105, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!105 = distinct !{!105, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!106 = distinct !{!106, !107, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!107 = distinct !{!107, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!108 = distinct !{!108, !109, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!109 = distinct !{!109, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!110 = !{!111, !113, !115}
!111 = distinct !{!111, !112, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!112 = distinct !{!112, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!113 = distinct !{!113, !114, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!114 = distinct !{!114, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!115 = distinct !{!115, !116, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!116 = distinct !{!116, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!117 = !{!118, !120, !122}
!118 = distinct !{!118, !119, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!119 = distinct !{!119, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!120 = distinct !{!120, !121, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!121 = distinct !{!121, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!122 = distinct !{!122, !123, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!123 = distinct !{!123, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!124 = !{!125, !127, !129}
!125 = distinct !{!125, !126, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka: %agg.result"}
!126 = distinct !{!126, !"_ZN3aie6detail18load_vector_helperIU3AS5aLj32EL15aie_dm_resource0EE3runEPU3AS5Ka"}
!127 = distinct !{!127, !128, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_: %agg.result"}
!128 = distinct !{!128, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS5aEEDaPKT1_"}
!129 = distinct !{!129, !130, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_: %agg.result"}
!130 = distinct !{!130, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS5aEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS5_"}
!131 = distinct !{!131, !132, !133}
!132 = !{!"llvm.loop.mustprogress"}
!133 = !{!"llvm.loop.itercount.range", i64 3}
