; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

; ModuleID = '/scratch/peano-tests/VITIS_AIE_QOR_MLLIB/mllib_gen-ir_peano/L1/regression/conv/Conv2D_bf16xbfp16_0/Work/aie/0_0/Release/Conv2D_bf16xbfp16_0.bc'
source_filename = "Work/aie/0_0/src/0_0.cc"
target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p-none-unknown-elf"

$_Z11conv2d_bf16ILh1EL5act_t0E8bfloat16S1_S1_Lb1ELb0ELb0ELb0ELb1EEvPT1_PT2_PT3_R18conv2d_bf16_paramsS7_S7_ = comdat any

; Function Attrs: nounwind willreturn memory(inaccessiblemem: write)
declare void @llvm.aie2p.set.ctrl.reg(i32, i32) #0

; Function Attrs: mustprogress
define weak_odr dso_local void @_Z11conv2d_bf16ILh1EL5act_t0E8bfloat16S1_S1_Lb1ELb0ELb0ELb0ELb1EEvPT1_PT2_PT3_R18conv2d_bf16_paramsS7_S7_(ptr noalias %ifm, ptr noalias %wts, ptr noalias %ofm, ptr nonnull align 64 dereferenceable(448) %conv2d_params, ptr noalias %psum_0_tdm, ptr noalias %psum_1_tdm) local_unnamed_addr #1 comdat {
entry:
  %0 = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 92
  %1 = load i32, ptr %0, align 4, !tbaa !4
  %add.i = add i32 %1, 16777216
  store i32 %add.i, ptr %0, align 4, !tbaa !4
  %shr.i = lshr i32 %add.i, 24
  %num_ifm_depth_iters.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 11
  %2 = load i8, ptr %num_ifm_depth_iters.i, align 1, !tbaa !7
  %conv2.i = zext i8 %2 to i32
  %cmp.i = icmp ugt i8 %2, 1
  %cmp5.i = icmp eq i32 %shr.i, 1
  %conv6.i = zext i1 %cmp5.i to i8
  %cmp10.i = icmp eq i32 %shr.i, %conv2.i
  %mul.i = select i1 %cmp10.i, i8 2, i8 0
  %add12.i = or disjoint i8 %mul.i, %conv6.i
  %cmp14.i = icmp ugt i32 %add.i, 33554431
  %cmp18.i = icmp samesign ult i32 %shr.i, %conv2.i
  %3 = select i1 %cmp14.i, i1 %cmp18.i, i1 false
  %conv19.i = select i1 %3, i8 3, i8 0
  %cmp23.i = icmp ugt i32 %1, -16777217
  %4 = select i1 %cmp23.i, i1 %cmp.i, i1 false
  %conv29.i = select i1 %4, i8 4, i8 0
  %add21.i = or disjoint i8 %add12.i, %conv29.i
  %add31.i = add nuw nsw i8 %add21.i, %conv19.i
  %conv33.i = select i1 %cmp.i, i8 %add31.i, i8 0
  %io_mode.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 96
  store i8 %conv33.i, ptr %io_mode.i, align 32, !tbaa !14
  %narrow.i = icmp samesign ugt i8 %conv33.i, 1
  %not..i = zext i1 %narrow.i to i32
  %psum_in.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 76
  store i32 %not..i, ptr %psum_in.i, align 4, !tbaa !15
  %out_mode.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 8
  %5 = load i8, ptr %out_mode.i, align 8, !tbaa !16
  %cmp63.i = icmp eq i8 %5, 1
  %or.cond.i = select i1 %cmp63.i, i1 %cmp10.i, i1 false
  br i1 %or.cond.i, label %if.end.i, label %if.else.i

if.else.i:                                        ; preds = %entry
  %conv_type.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 16
  %6 = load i8, ptr %conv_type.i, align 16, !tbaa !17
  %7 = add i8 %6, -4
  %8 = icmp ult i8 %7, -2
  %cmp49.i = icmp ne i8 %6, 8
  %mulbool142.i = and i1 %cmp49.i, %8
  %cmp59.i = icmp ne i8 %6, 5
  %mulbool.i = and i1 %cmp59.i, %mulbool142.i
  %9 = and i8 %conv33.i, 13
  %narrow144.i = icmp ne i8 %9, 0
  %not.143.i = zext i1 %narrow144.i to i32
  %cmp85.i = icmp eq i8 %6, 12
  %10 = shl i8 %6, 4
  %cmp91.not.i = icmp eq i8 %6, 3
  %11 = or i1 %cmp91.not.i, %cmp85.i
  %mul93.i = select i1 %11, i8 0, i8 %10
  %mul94.i = select i1 %mulbool.i, i8 %mul93.i, i8 0
  %add98.i = or disjoint i8 %mul94.i, %conv33.i
  br label %if.end.i

if.end.i:                                         ; preds = %if.else.i, %entry
  %not.143.sink.i = phi i32 [ %not.143.i, %if.else.i ], [ 1, %entry ]
  %add98.sink.i = phi i8 [ %add98.i, %if.else.i ], [ 1, %entry ]
  %12 = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 80
  store i32 %not.143.sink.i, ptr %12, align 16, !tbaa !18
  %13 = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 104
  store i8 %add98.sink.i, ptr %13, align 8, !tbaa !19
  br i1 %cmp10.i, label %if.then106.i, label %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit

if.then106.i:                                     ; preds = %if.end.i
  %and.i = and i32 %1, 16777215
  store i32 %and.i, ptr %0, align 4, !tbaa !4
  br label %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit

_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit: ; preds = %if.then106.i, %if.end.i
  %ifm_offset = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 116
  %14 = load i32, ptr %ifm_offset, align 4, !tbaa !20
  %hdr_len = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 84
  %15 = load i32, ptr %hdr_len, align 4, !tbaa !21
  %wts_offset = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 120
  %16 = load i32, ptr %wts_offset, align 8, !tbaa !22
  %17 = add i8 %add98.sink.i, -1
  %switch.and = and i8 %17, -3
  %idx.ext2 = trunc i32 %15 to i20
  %add.ptr3 = getelementptr inbounds i32, ptr %wts, i20 %idx.ext2
  %idx.ext5 = trunc i32 %16 to i20
  %add.ptr6 = getelementptr inbounds i32, ptr %add.ptr3, i20 %idx.ext5
  %idx.ext = trunc i32 %14 to i20
  %add.ptr = getelementptr inbounds i32, ptr %ifm, i20 %idx.ext
  tail call void @llvm.experimental.noalias.scope.decl(metadata !23)
  tail call void @llvm.experimental.noalias.scope.decl(metadata !26)
  tail call void @llvm.experimental.noalias.scope.decl(metadata !28)
  tail call void @llvm.experimental.noalias.scope.decl(metadata !30)
  %internal_param.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 64
  %18 = load i32, ptr %internal_param.i, align 64, !tbaa !32, !noalias !33
  %cmp.i19 = icmp eq i32 %18, 1
  %spec.select.i = select i1 %cmp.i19, bfloat 0xRFF7F, bfloat 0xR0000
  %not.narrow.i = xor i1 %narrow.i, true
  %sub.i = zext i1 %not.narrow.i to i32
  %19 = addrspacecast ptr %psum_0_tdm to ptr addrspace(5)
  %20 = addrspacecast ptr %psum_1_tdm to ptr addrspace(7)
  %bias_len.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 260
  %21 = load i16, ptr %bias_len.i, align 4, !tbaa !35, !noalias !33
  %idx.ext.i = zext i16 %21 to i20
  %idx.neg.i = sub nsw i20 0, %idx.ext.i
  %add.ptr.i = getelementptr inbounds i32, ptr %add.ptr6, i20 %idx.neg.i
  tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 11)
  %bf_to_bfp.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 352
  tail call void @_Z21convert_bf16_to_bfp16I8bfloat16Lb0EEvPT_PS0_RK13BfToBfpParams(ptr %add.ptr, ptr %add.ptr, ptr nonnull align 32 dereferenceable(32) %bf_to_bfp.i) #9, !noalias !36
  tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 12)
  %dimsAI7.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 268
  %dimsAI.sroa.0.0.copyload.i = load i32, ptr %dimsAI7.i, align 4, !tbaa !37, !noalias !33
  %dimsAI.sroa.7.0.dimsAI7.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 272
  %dimsAI.sroa.7.0.copyload.i = load i32, ptr %dimsAI.sroa.7.0.dimsAI7.sroa_idx.i, align 16, !tbaa !37, !noalias !33
  %dimsAI.sroa.11.0.dimsAI7.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 276
  %dimsAI.sroa.11.0.copyload.i = load i32, ptr %dimsAI.sroa.11.0.dimsAI7.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsAI.sroa.15.0.dimsAI7.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 280
  %dimsAI.sroa.15.0.copyload.i = load i32, ptr %dimsAI.sroa.15.0.dimsAI7.sroa_idx.i, align 8, !tbaa !37, !noalias !33
  %dimsAI.sroa.19.0.dimsAI7.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 284
  %dimsAI.sroa.19.0.copyload.i = load i32, ptr %dimsAI.sroa.19.0.dimsAI7.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsAI.sroa.23.0.dimsAI7.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 288
  %dimsAI.sroa.23.0.copyload.i = load i32, ptr %dimsAI.sroa.23.0.dimsAI7.sroa_idx.i, align 32, !tbaa !37, !noalias !33
  %dimsAI.sroa.31.0.dimsAI7.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 292
  %dimsAI.sroa.31.0.copyload.i = load i32, ptr %dimsAI.sroa.31.0.dimsAI7.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsAO9.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 296
  %dimsAO.sroa.0.0.copyload.i = load i32, ptr %dimsAO9.i, align 8, !tbaa !37, !noalias !33
  %dimsAO.sroa.4.0.dimsAO9.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 300
  %dimsAO.sroa.4.0.copyload.i = load i32, ptr %dimsAO.sroa.4.0.dimsAO9.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsAO.sroa.5.0.dimsAO9.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 304
  %dimsAO.sroa.5.0.copyload.i = load i32, ptr %dimsAO.sroa.5.0.dimsAO9.sroa_idx.i, align 16, !tbaa !37, !noalias !33
  %dimsAO.sroa.6.0.dimsAO9.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 308
  %dimsAO.sroa.6.0.copyload.i = load i32, ptr %dimsAO.sroa.6.0.dimsAO9.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsAO.sroa.7.0.dimsAO9.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 312
  %dimsAO.sroa.7.0.copyload.i = load i32, ptr %dimsAO.sroa.7.0.dimsAO9.sroa_idx.i, align 8, !tbaa !37, !noalias !33
  %dimsAO.sroa.8.0.dimsAO9.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 316
  %dimsAO.sroa.8.0.copyload.i = load i32, ptr %dimsAO.sroa.8.0.dimsAO9.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsAO.sroa.10.0.dimsAO9.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 320
  %dimsAO.sroa.10.0.copyload.i = load i32, ptr %dimsAO.sroa.10.0.dimsAO9.sroa_idx.i, align 64, !tbaa !37, !noalias !33
  %dimsW11.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 324
  %dimsW.sroa.0.0.copyload.i = load i32, ptr %dimsW11.i, align 4, !tbaa !37, !noalias !33
  %dimsW.sroa.4.0.dimsW11.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 328
  %dimsW.sroa.4.0.copyload.i = load i32, ptr %dimsW.sroa.4.0.dimsW11.sroa_idx.i, align 8, !tbaa !37, !noalias !33
  %dimsW.sroa.5.0.dimsW11.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 332
  %dimsW.sroa.5.0.copyload.i = load i32, ptr %dimsW.sroa.5.0.dimsW11.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsW.sroa.6.0.dimsW11.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 336
  %dimsW.sroa.6.0.copyload.i = load i32, ptr %dimsW.sroa.6.0.dimsW11.sroa_idx.i, align 16, !tbaa !37, !noalias !33
  %dimsW.sroa.7.0.dimsW11.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 340
  %dimsW.sroa.7.0.copyload.i = load i32, ptr %dimsW.sroa.7.0.dimsW11.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %dimsW.sroa.8.0.dimsW11.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 344
  %dimsW.sroa.8.0.copyload.i = load i32, ptr %dimsW.sroa.8.0.dimsW11.sroa_idx.i, align 8, !tbaa !37, !noalias !33
  %dimsW.sroa.10.0.dimsW11.sroa_idx.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 348
  %dimsW.sroa.10.0.copyload.i = load i32, ptr %dimsW.sroa.10.0.dimsW11.sroa_idx.i, align 4, !tbaa !37, !noalias !33
  %conv_type.i21 = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 16
  %22 = load i8, ptr %conv_type.i21, align 16, !tbaa !17, !noalias !33
  %inc_ST_015.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 200
  %23 = load i32, ptr %inc_ST_015.i, align 8, !tbaa !38, !noalias !33
  %inc_ST_117.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 204
  %24 = load i32, ptr %inc_ST_117.i, align 4, !tbaa !39, !noalias !33
  %inc_Xo_T.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 196
  %25 = load i32, ptr %inc_Xo_T.i, align 4, !tbaa !40, !noalias !33
  %num_X.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 256
  %26 = load i32, ptr %num_X.i, align 64, !tbaa !41, !noalias !33
  %inc_Co_T.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 192
  %27 = load i32, ptr %inc_Co_T.i, align 64, !tbaa !42, !noalias !33
  %outer_g.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 112
  %28 = load i32, ptr %outer_g.i, align 16, !tbaa !43, !noalias !33
  %29 = icmp ugt i32 %28, 1
  tail call void @llvm.assume(i1 %29)
  %30 = trunc i32 %dimsAI.sroa.19.0.copyload.i to i20
  %31 = trunc i32 %dimsAI.sroa.0.0.copyload.i to i20
  %32 = trunc i32 %dimsAI.sroa.7.0.copyload.i to i20
  %33 = trunc i32 %dimsAI.sroa.11.0.copyload.i to i20
  %34 = trunc i32 %dimsAI.sroa.15.0.copyload.i to i20
  %shfl_0.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 236
  %35 = load i32, ptr %shfl_0.i, align 4, !tbaa !44, !noalias !33
  %shfl_1.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 240
  %36 = load i32, ptr %shfl_1.i, align 16, !tbaa !45, !noalias !33
  %or19.i.i.i = or disjoint i32 %sub.i, 780
  %inner_g.i = getelementptr inbounds nuw i8, ptr %conv2d_params, i20 108
  %37 = load i32, ptr %inner_g.i, align 4, !tbaa !46, !noalias !33
  %38 = icmp ugt i32 %37, 7
  tail call void @llvm.assume(i1 %38)
  %39 = trunc i32 %dimsAO.sroa.7.0.copyload.i to i20
  %40 = trunc i32 %dimsAO.sroa.4.0.copyload.i to i20
  %41 = trunc i32 %dimsAO.sroa.6.0.copyload.i to i20
  %42 = trunc i32 %dimsAO.sroa.0.0.copyload.i to i20
  %43 = trunc i32 %dimsAO.sroa.5.0.copyload.i to i20
  %44 = trunc i32 %dimsW.sroa.7.0.copyload.i to i20
  %45 = trunc i32 %dimsW.sroa.4.0.copyload.i to i20
  %46 = trunc i32 %dimsW.sroa.6.0.copyload.i to i20
  %47 = trunc i32 %dimsW.sroa.0.0.copyload.i to i20
  %48 = trunc i32 %dimsW.sroa.5.0.copyload.i to i20
  br label %for.body.i

for.cond.cleanup.i:                               ; preds = %for.cond.cleanup151.i
  %switch.selectcmp.not = icmp eq i8 %switch.and, 0
  %splat.splatinsert.i.i = insertelement <32 x bfloat> poison, bfloat %spec.select.i, i64 0
  %splat.splat.i.i = shufflevector <32 x bfloat> %splat.splatinsert.i.i, <32 x bfloat> poison, <32 x i32> zeroinitializer
  br i1 %switch.selectcmp.not, label %_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t.exit, label %for.cond219.preheader.i

for.cond219.preheader.i:                          ; preds = %for.cond.cleanup.i
  %add22.i = add nsw i32 %24, %23
  %cmp13.i = icmp eq i8 %22, 12
  %sub28.i = add i32 %27, 1048512
  %sub25.i = add i32 %25, 1048512
  %cond.i = select i1 %cmp13.i, i32 -128, i32 0
  %add.i23 = add nsw i32 %cond.i, %23
  %add23.i = add nsw i32 %add.i23, 64
  %idx.ext.i960.i = trunc i32 %add.i23 to i20
  %idx.ext.i964.i = trunc i32 %add23.i to i20
  %idx.ext.i972.i = trunc i32 %add22.i to i20
  %49 = trunc i32 %sub28.i to i20
  %50 = trunc i32 %sub25.i to i20
  %51 = trunc i32 %26 to i20
  br label %for.body224.i

for.body.i:                                       ; preds = %for.cond.cleanup151.i, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit
  %p_sum_in_0.01132.i = phi ptr addrspace(5) [ %19, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %add.ptr.ascast.i704.i, %for.cond.cleanup151.i ]
  %p_sum_in_1.01131.i = phi ptr addrspace(7) [ %20, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %add.ptr.ascast.i736.i, %for.cond.cleanup151.i ]
  %p_sum_out_0.01130.i = phi ptr addrspace(5) [ %19, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %add.ptr.ascast.i846.i, %for.cond.cleanup151.i ]
  %p_sum_out_1.01129.i = phi ptr addrspace(7) [ %20, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %add.ptr.ascast.i870.i, %for.cond.cleanup151.i ]
  %j.01128.i = phi i32 [ 0, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %inc214.i, %for.cond.cleanup151.i ]
  %pA.0.in1127.i = phi ptr [ %add.ptr, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %232, %for.cond.cleanup151.i ]
  %pW.0.in1126.i = phi ptr [ %add.ptr6, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %241, %for.cond.cleanup151.i ]
  %fA.sroa.34.01125.i = phi i32 [ 0, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %fA.sroa.34.1.i, %for.cond.cleanup151.i ]
  %fA.sroa.0.01124.i = phi <32 x i32> [ undef, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %fA.sroa.0.1.i, %for.cond.cleanup151.i ]
  %fW.sroa.26.01123.i = phi i32 [ 0, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %fW.sroa.26.1.i, %for.cond.cleanup151.i ]
  %fW.sroa.0.01122.i = phi <32 x i32> [ undef, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %fW.sroa.0.1.i, %for.cond.cleanup151.i ]
  %dimsAI.sroa.31.01121.i = phi i32 [ %dimsAI.sroa.31.0.copyload.i, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %274, %for.cond.cleanup151.i ]
  %dimsAI.sroa.23.01120.i = phi i32 [ %dimsAI.sroa.23.0.copyload.i, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %272, %for.cond.cleanup151.i ]
  %dimsAO.sroa.10.01119.i = phi i32 [ %dimsAO.sroa.10.0.copyload.i, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %231, %for.cond.cleanup151.i ]
  %dimsAO.sroa.8.01118.i = phi i32 [ %dimsAO.sroa.8.0.copyload.i, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %229, %for.cond.cleanup151.i ]
  %dimsW.sroa.10.01117.i = phi i32 [ %dimsW.sroa.10.0.copyload.i, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %240, %for.cond.cleanup151.i ]
  %dimsW.sroa.8.01116.i = phi i32 [ %dimsW.sroa.8.0.copyload.i, %_Z29setup_conv2d_bf16_iter_paramsR18conv2d_bf16_params.exit ], [ %238, %for.cond.cleanup151.i ]
  %pA.0.i = addrspacecast ptr %pA.0.in1127.i to ptr addrspace(5)
  %pW.0.i = addrspacecast ptr %pW.0.in1126.i to ptr addrspace(6)
  %52 = load <8 x i64>, ptr addrspace(5) %p_sum_in_0.01132.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %53 = addrspacecast ptr addrspace(5) %p_sum_in_0.01132.i to ptr
  %add.ptr.i.i = getelementptr inbounds nuw i8, ptr %53, i20 64
  %add.ptr.ascast.i.i = addrspacecast ptr %add.ptr.i.i to ptr addrspace(5)
  %54 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle6.i.i.i = shufflevector <8 x i64> %52, <8 x i64> %54, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i681.i = getelementptr inbounds nuw i8, ptr %53, i20 128
  %add.ptr.ascast.i682.i = addrspacecast ptr %add.ptr.i681.i to ptr addrspace(5)
  %55 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i682.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle1.i.i683.i = shufflevector <8 x i64> %55, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i.i = shufflevector <32 x i64> %shuffle6.i.i.i, <32 x i64> %shuffle1.i.i683.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i684.i = getelementptr inbounds nuw i8, ptr %53, i20 192
  %add.ptr.ascast.i685.i = addrspacecast ptr %add.ptr.i684.i to ptr addrspace(5)
  %56 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i685.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle1.i.i686.i = shufflevector <8 x i64> %56, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i.i = shufflevector <32 x i64> %shuffle11.i.i.i, <32 x i64> %shuffle1.i.i686.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %add.ptr.i687.i = getelementptr inbounds nuw i8, ptr %53, i20 256
  %add.ptr.ascast.i688.i = addrspacecast ptr %add.ptr.i687.i to ptr addrspace(5)
  %57 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i688.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i691.i = getelementptr inbounds nuw i8, ptr %53, i20 320
  %add.ptr.ascast.i692.i = addrspacecast ptr %add.ptr.i691.i to ptr addrspace(5)
  %58 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i692.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle6.i.i694.i = shufflevector <8 x i64> %57, <8 x i64> %58, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i695.i = getelementptr inbounds nuw i8, ptr %53, i20 384
  %add.ptr.ascast.i696.i = addrspacecast ptr %add.ptr.i695.i to ptr addrspace(5)
  %59 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i696.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle1.i.i697.i = shufflevector <8 x i64> %59, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i698.i = shufflevector <32 x i64> %shuffle6.i.i694.i, <32 x i64> %shuffle1.i.i697.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i699.i = getelementptr inbounds nuw i8, ptr %53, i20 448
  %add.ptr.ascast.i700.i = addrspacecast ptr %add.ptr.i699.i to ptr addrspace(5)
  %60 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i700.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle1.i.i701.i = shufflevector <8 x i64> %60, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i702.i = shufflevector <32 x i64> %shuffle11.i.i698.i, <32 x i64> %shuffle1.i.i701.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %61 = load <8 x i64>, ptr addrspace(7) %p_sum_in_1.01131.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %62 = addrspacecast ptr addrspace(7) %p_sum_in_1.01131.i to ptr
  %add.ptr.i707.i = getelementptr inbounds nuw i8, ptr %62, i20 64
  %add.ptr.ascast.i708.i = addrspacecast ptr %add.ptr.i707.i to ptr addrspace(7)
  %63 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i708.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle6.i.i710.i = shufflevector <8 x i64> %61, <8 x i64> %63, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i711.i = getelementptr inbounds nuw i8, ptr %62, i20 128
  %add.ptr.ascast.i712.i = addrspacecast ptr %add.ptr.i711.i to ptr addrspace(7)
  %64 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i712.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle1.i.i713.i = shufflevector <8 x i64> %64, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i714.i = shufflevector <32 x i64> %shuffle6.i.i710.i, <32 x i64> %shuffle1.i.i713.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i715.i = getelementptr inbounds nuw i8, ptr %62, i20 192
  %add.ptr.ascast.i716.i = addrspacecast ptr %add.ptr.i715.i to ptr addrspace(7)
  %65 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i716.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle1.i.i717.i = shufflevector <8 x i64> %65, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i718.i = shufflevector <32 x i64> %shuffle11.i.i714.i, <32 x i64> %shuffle1.i.i717.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %add.ptr.i719.i = getelementptr inbounds nuw i8, ptr %62, i20 256
  %add.ptr.ascast.i720.i = addrspacecast ptr %add.ptr.i719.i to ptr addrspace(7)
  %66 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i720.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i723.i = getelementptr inbounds nuw i8, ptr %62, i20 320
  %add.ptr.ascast.i724.i = addrspacecast ptr %add.ptr.i723.i to ptr addrspace(7)
  %67 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i724.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle6.i.i726.i = shufflevector <8 x i64> %66, <8 x i64> %67, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i727.i = getelementptr inbounds nuw i8, ptr %62, i20 384
  %add.ptr.ascast.i728.i = addrspacecast ptr %add.ptr.i727.i to ptr addrspace(7)
  %68 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i728.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle1.i.i729.i = shufflevector <8 x i64> %68, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i730.i = shufflevector <32 x i64> %shuffle6.i.i726.i, <32 x i64> %shuffle1.i.i729.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %add.ptr.i731.i = getelementptr inbounds nuw i8, ptr %62, i20 448
  %add.ptr.ascast.i732.i = addrspacecast ptr %add.ptr.i731.i to ptr addrspace(7)
  %69 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i732.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle1.i.i733.i = shufflevector <8 x i64> %69, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i734.i = shufflevector <32 x i64> %shuffle11.i.i730.i, <32 x i64> %shuffle1.i.i733.i, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %mul.i22 = shl nsw i32 %dimsW.sroa.10.01117.i, 7
  %idx.ext.i.i = trunc i32 %mul.i22 to i20
  %add.ptr.i737.i = getelementptr inbounds i8, ptr %add.ptr.i, i20 %idx.ext.i.i
  %add.ptr.ascast.i738.i = addrspacecast ptr %add.ptr.i737.i to ptr addrspace(6)
  %70 = load <32 x bfloat>, ptr addrspace(6) %add.ptr.ascast.i738.i, align 64, !tbaa !4, !alias.scope !23, !noalias !49
  %71 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %70)
  %72 = bitcast <32 x float> %71 to <16 x i64>
  %shuffle2.i.i741.i = shufflevector <16 x i64> %72, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i742.i = getelementptr inbounds nuw i8, ptr %add.ptr.i737.i, i20 64
  %add.ptr.ascast.i743.i = addrspacecast ptr %add.ptr.i742.i to ptr addrspace(6)
  %73 = load <32 x bfloat>, ptr addrspace(6) %add.ptr.ascast.i743.i, align 64, !tbaa !4, !alias.scope !23, !noalias !49
  %74 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %73)
  %75 = bitcast <32 x float> %74 to <16 x i64>
  %shuffle2.i.i747.i = shufflevector <16 x i64> %75, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %76 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %pA.0.i, <32 x i32> %fA.sroa.0.01124.i, i32 %fA.sroa.34.01125.i)
  %77 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %76, 0
  %78 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %76, 1
  %79 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %76, 2
  %80 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %77, <32 x i32> %78, i32 %79)
  %81 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %80, 0
  %82 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %80, 1
  %83 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %80, 2
  %84 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) %pW.0.i, <32 x i32> %fW.sroa.0.01122.i, i32 %fW.sroa.26.01123.i)
  %85 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %84, 0
  %86 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %84, 1
  %87 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %84, 2
  %88 = tail call { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p5.p5(ptr addrspace(5) %81, <32 x i32> %82, i32 %83)
  %89 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %88, 0
  %90 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %88, 1
  %91 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %88, 2
  %92 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %88, 3
  %93 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %88, 4
  %94 = trunc i32 %dimsAI.sroa.23.01120.i to i20
  %95 = trunc i32 %dimsAI.sroa.31.01121.i to i20
  %96 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) %89, <32 x i32> %90, i32 %91, i20 %30, i20 %31, i20 %94, i20 %32, i20 %33, i20 %95, i20 %34)
  %97 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %96, 0
  %98 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %96, 1
  %99 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %96, 2
  %100 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %96, 5
  %101 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %96, 6
  %102 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %96, 3
  %103 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %96, 4
  %104 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p6.p6(ptr addrspace(6) %85, <32 x i32> %86, i32 %87)
  %105 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %104, 0
  %106 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %104, 1
  %107 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %104, 2
  %108 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %104, 3
  %109 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %104, 4
  %110 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p6.p6(ptr addrspace(6) %105, <32 x i32> %106, i32 %107, i20 0)
  %111 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %110, 0
  %112 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %110, 1
  %113 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %110, 2
  %114 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %110, 3
  %115 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %110, 4
  %116 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %92, <8 x i8> %93, <64 x i8> %100, <8 x i8> %101, i32 %35)
  %117 = extractvalue { <64 x i8>, <8 x i8> } %116, 0
  %118 = extractvalue { <64 x i8>, <8 x i8> } %116, 1
  %119 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %92, <8 x i8> %93, <64 x i8> %100, <8 x i8> %101, i32 %36)
  %120 = extractvalue { <64 x i8>, <8 x i8> } %119, 0
  %121 = extractvalue { <64 x i8>, <8 x i8> } %119, 1
  %122 = bitcast <32 x i64> %shuffle12.i.i.i to <64 x i32>
  %123 = bitcast <32 x i64> %shuffle2.i.i741.i to <64 x i32>
  %124 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %117, <8 x i8> %118, <64 x i8> %108, <8 x i8> %109, <64 x i32> %122, <64 x i32> %123, i32 %or19.i.i.i)
  %125 = bitcast <32 x i64> %shuffle12.i.i702.i to <64 x i32>
  %126 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %120, <8 x i8> %121, <64 x i8> %108, <8 x i8> %109, <64 x i32> %125, <64 x i32> %123, i32 %or19.i.i.i)
  %127 = bitcast <32 x i64> %shuffle12.i.i718.i to <64 x i32>
  %128 = bitcast <32 x i64> %shuffle2.i.i747.i to <64 x i32>
  %129 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %117, <8 x i8> %118, <64 x i8> %114, <8 x i8> %115, <64 x i32> %127, <64 x i32> %128, i32 %or19.i.i.i)
  %130 = bitcast <32 x i64> %shuffle12.i.i734.i to <64 x i32>
  %131 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %120, <8 x i8> %121, <64 x i8> %114, <8 x i8> %115, <64 x i32> %130, <64 x i32> %128, i32 %or19.i.i.i)
  %132 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %97, <32 x i32> %98, i32 %99)
  %133 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %132, 0
  %134 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %132, 1
  %135 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %132, 2
  %136 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %133, <32 x i32> %134, i32 %135)
  %137 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %136, 0
  %138 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %136, 1
  %139 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %136, 2
  %140 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) %111, <32 x i32> %112, i32 %113)
  %141 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %140, 0
  %142 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %140, 1
  %143 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %140, 2
  %144 = tail call { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p5.p5(ptr addrspace(5) %137, <32 x i32> %138, i32 %139)
  %145 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %144, 0
  %146 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %144, 1
  %147 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %144, 2
  %148 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %144, 3
  %149 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %144, 4
  %150 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) %145, <32 x i32> %146, i32 %147, i20 %30, i20 %31, i20 %102, i20 %32, i20 %33, i20 %103, i20 %34)
  %151 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %150, 0
  %152 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %150, 1
  %153 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %150, 2
  %154 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %150, 5
  %155 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %150, 6
  %156 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %150, 3
  %157 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %150, 4
  %158 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p6.p6(ptr addrspace(6) %141, <32 x i32> %142, i32 %143)
  %159 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %158, 0
  %160 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %158, 1
  %161 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %158, 2
  %162 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %158, 3
  %163 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %158, 4
  %164 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p6.p6(ptr addrspace(6) %159, <32 x i32> %160, i32 %161, i20 0)
  %165 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %164, 0
  %166 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %164, 1
  %167 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %164, 2
  %168 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %164, 3
  %169 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %164, 4
  %170 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %148, <8 x i8> %149, <64 x i8> %154, <8 x i8> %155, i32 %35)
  %171 = extractvalue { <64 x i8>, <8 x i8> } %170, 0
  %172 = extractvalue { <64 x i8>, <8 x i8> } %170, 1
  %173 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %148, <8 x i8> %149, <64 x i8> %154, <8 x i8> %155, i32 %36)
  %174 = extractvalue { <64 x i8>, <8 x i8> } %173, 0
  %175 = extractvalue { <64 x i8>, <8 x i8> } %173, 1
  %176 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %171, <8 x i8> %172, <64 x i8> %162, <8 x i8> %163, <64 x i32> %124, i32 780)
  %177 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %174, <8 x i8> %175, <64 x i8> %162, <8 x i8> %163, <64 x i32> %126, i32 780)
  %178 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %171, <8 x i8> %172, <64 x i8> %168, <8 x i8> %169, <64 x i32> %129, i32 780)
  %179 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %174, <8 x i8> %175, <64 x i8> %168, <8 x i8> %169, <64 x i32> %131, i32 780)
  %180 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %151, <32 x i32> %152, i32 %153)
  %181 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %180, 0
  %182 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %180, 1
  %183 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %180, 2
  %184 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %181, <32 x i32> %182, i32 %183)
  %185 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %184, 0
  %186 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %184, 1
  %187 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %184, 2
  %188 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) %165, <32 x i32> %166, i32 %167)
  %189 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %188, 0
  %190 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %188, 1
  %191 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %188, 2
  %192 = tail call { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p5.p5(ptr addrspace(5) %185, <32 x i32> %186, i32 %187)
  %193 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %192, 0
  %194 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %192, 1
  %195 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %192, 2
  %196 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %192, 3
  %197 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %192, 4
  %198 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) %193, <32 x i32> %194, i32 %195, i20 %30, i20 %31, i20 %156, i20 %32, i20 %33, i20 %157, i20 %34)
  %199 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %198, 5
  %200 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %198, 6
  %201 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %198, 3
  %202 = zext i20 %201 to i32
  %203 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %198, 4
  %204 = zext i20 %203 to i32
  %205 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p6.p6(ptr addrspace(6) %189, <32 x i32> %190, i32 %191)
  %206 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %205, 0
  %207 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %205, 1
  %208 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %205, 2
  %209 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %205, 3
  %210 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %205, 4
  %211 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p6.p6(ptr addrspace(6) %206, <32 x i32> %207, i32 %208, i20 0)
  %212 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %211, 3
  %213 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %211, 4
  %214 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %196, <8 x i8> %197, <64 x i8> %199, <8 x i8> %200, i32 %35)
  %215 = extractvalue { <64 x i8>, <8 x i8> } %214, 0
  %216 = extractvalue { <64 x i8>, <8 x i8> } %214, 1
  %217 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %196, <8 x i8> %197, <64 x i8> %199, <8 x i8> %200, i32 %36)
  %218 = extractvalue { <64 x i8>, <8 x i8> } %217, 0
  %219 = extractvalue { <64 x i8>, <8 x i8> } %217, 1
  %220 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %215, <8 x i8> %216, <64 x i8> %209, <8 x i8> %210, <64 x i32> %176, i32 780)
  %221 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %218, <8 x i8> %219, <64 x i8> %209, <8 x i8> %210, <64 x i32> %177, i32 780)
  %222 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %215, <8 x i8> %216, <64 x i8> %212, <8 x i8> %213, <64 x i32> %178, i32 780)
  %223 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %218, <8 x i8> %219, <64 x i8> %212, <8 x i8> %213, <64 x i32> %179, i32 780)
  %pA.11097.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %198, 0
  %pW.11098.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %211, 0
  %fA.sroa.34.11099.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %198, 2
  %fA.sroa.0.11100.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %198, 1
  %fW.sroa.26.11101.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %211, 2
  %fW.sroa.0.11102.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %211, 1
  br label %for.body152.i

for.cond.cleanup151.i:                            ; preds = %for.body152.i
  %add.ptr.i703.i = getelementptr inbounds nuw i8, ptr %53, i20 512
  %add.ptr.i735.i = getelementptr inbounds nuw i8, ptr %62, i20 512
  %add.ptr.ascast.i704.i = addrspacecast ptr %add.ptr.i703.i to ptr addrspace(5)
  %add.ptr.ascast.i736.i = addrspacecast ptr %add.ptr.i735.i to ptr addrspace(7)
  %224 = addrspacecast ptr addrspace(5) %pA.1.i to ptr
  %225 = trunc i32 %dimsAO.sroa.8.01118.i to i20
  %226 = trunc i32 %dimsAO.sroa.10.01119.i to i20
  %227 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr %224, i20 %39, i20 %40, i20 %41, i20 %42, i20 %225, i20 %43, i20 %226)
  %228 = extractvalue { ptr, i20, i20 } %227, 1
  %229 = zext i20 %228 to i32
  %230 = extractvalue { ptr, i20, i20 } %227, 2
  %231 = zext i20 %230 to i32
  %232 = extractvalue { ptr, i20, i20 } %227, 0
  %233 = addrspacecast ptr addrspace(6) %pW.1.i to ptr
  %234 = trunc i32 %dimsW.sroa.8.01116.i to i20
  %235 = trunc i32 %dimsW.sroa.10.01117.i to i20
  %236 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr %233, i20 %44, i20 %45, i20 %46, i20 %47, i20 %234, i20 %48, i20 %235)
  %237 = extractvalue { ptr, i20, i20 } %236, 1
  %238 = zext i20 %237 to i32
  %239 = extractvalue { ptr, i20, i20 } %236, 2
  %240 = zext i20 %239 to i32
  %241 = extractvalue { ptr, i20, i20 } %236, 0
  %242 = bitcast <64 x i32> %290 to <32 x i64>
  %shuffle.i.i826.i = shufflevector <32 x i64> %242, <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  store <8 x i64> %shuffle.i.i826.i, ptr addrspace(5) %p_sum_out_0.01130.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %243 = addrspacecast ptr addrspace(5) %p_sum_out_0.01130.i to ptr
  %add.ptr.i827.i = getelementptr inbounds nuw i8, ptr %243, i20 64
  %add.ptr.ascast.i828.i = addrspacecast ptr %add.ptr.i827.i to ptr addrspace(5)
  %shuffle4.i.i.i = shufflevector <32 x i64> %242, <32 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <8 x i64> %shuffle4.i.i.i, ptr addrspace(5) %add.ptr.ascast.i828.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i829.i = getelementptr inbounds nuw i8, ptr %243, i20 128
  %add.ptr.ascast.i830.i = addrspacecast ptr %add.ptr.i829.i to ptr addrspace(5)
  %shuffle9.i.i.i = shufflevector <32 x i64> %242, <32 x i64> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  store <8 x i64> %shuffle9.i.i.i, ptr addrspace(5) %add.ptr.ascast.i830.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i831.i = getelementptr inbounds nuw i8, ptr %243, i20 192
  %add.ptr.ascast.i832.i = addrspacecast ptr %add.ptr.i831.i to ptr addrspace(5)
  %shuffle10.i.i.i = shufflevector <32 x i64> %242, <32 x i64> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  store <8 x i64> %shuffle10.i.i.i, ptr addrspace(5) %add.ptr.ascast.i832.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i833.i = getelementptr inbounds nuw i8, ptr %243, i20 256
  %add.ptr.ascast.i834.i = addrspacecast ptr %add.ptr.i833.i to ptr addrspace(5)
  %244 = bitcast <64 x i32> %291 to <32 x i64>
  %shuffle.i.i835.i = shufflevector <32 x i64> %244, <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  store <8 x i64> %shuffle.i.i835.i, ptr addrspace(5) %add.ptr.ascast.i834.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i836.i = getelementptr inbounds nuw i8, ptr %243, i20 320
  %add.ptr.ascast.i837.i = addrspacecast ptr %add.ptr.i836.i to ptr addrspace(5)
  %shuffle4.i.i838.i = shufflevector <32 x i64> %244, <32 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <8 x i64> %shuffle4.i.i838.i, ptr addrspace(5) %add.ptr.ascast.i837.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i839.i = getelementptr inbounds nuw i8, ptr %243, i20 384
  %add.ptr.ascast.i840.i = addrspacecast ptr %add.ptr.i839.i to ptr addrspace(5)
  %shuffle9.i.i841.i = shufflevector <32 x i64> %244, <32 x i64> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  store <8 x i64> %shuffle9.i.i841.i, ptr addrspace(5) %add.ptr.ascast.i840.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i842.i = getelementptr inbounds nuw i8, ptr %243, i20 448
  %add.ptr.ascast.i843.i = addrspacecast ptr %add.ptr.i842.i to ptr addrspace(5)
  %shuffle10.i.i844.i = shufflevector <32 x i64> %244, <32 x i64> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  store <8 x i64> %shuffle10.i.i844.i, ptr addrspace(5) %add.ptr.ascast.i843.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i845.i = getelementptr inbounds nuw i8, ptr %243, i20 512
  %add.ptr.ascast.i846.i = addrspacecast ptr %add.ptr.i845.i to ptr addrspace(5)
  %245 = bitcast <64 x i32> %292 to <32 x i64>
  %shuffle.i.i847.i = shufflevector <32 x i64> %245, <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  store <8 x i64> %shuffle.i.i847.i, ptr addrspace(7) %p_sum_out_1.01129.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %246 = addrspacecast ptr addrspace(7) %p_sum_out_1.01129.i to ptr
  %add.ptr.i848.i = getelementptr inbounds nuw i8, ptr %246, i20 64
  %add.ptr.ascast.i849.i = addrspacecast ptr %add.ptr.i848.i to ptr addrspace(7)
  %shuffle4.i.i850.i = shufflevector <32 x i64> %245, <32 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <8 x i64> %shuffle4.i.i850.i, ptr addrspace(7) %add.ptr.ascast.i849.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i851.i = getelementptr inbounds nuw i8, ptr %246, i20 128
  %add.ptr.ascast.i852.i = addrspacecast ptr %add.ptr.i851.i to ptr addrspace(7)
  %shuffle9.i.i853.i = shufflevector <32 x i64> %245, <32 x i64> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  store <8 x i64> %shuffle9.i.i853.i, ptr addrspace(7) %add.ptr.ascast.i852.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i854.i = getelementptr inbounds nuw i8, ptr %246, i20 192
  %add.ptr.ascast.i855.i = addrspacecast ptr %add.ptr.i854.i to ptr addrspace(7)
  %shuffle10.i.i856.i = shufflevector <32 x i64> %245, <32 x i64> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  store <8 x i64> %shuffle10.i.i856.i, ptr addrspace(7) %add.ptr.ascast.i855.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i857.i = getelementptr inbounds nuw i8, ptr %246, i20 256
  %add.ptr.ascast.i858.i = addrspacecast ptr %add.ptr.i857.i to ptr addrspace(7)
  %247 = bitcast <64 x i32> %293 to <32 x i64>
  %shuffle.i.i859.i = shufflevector <32 x i64> %247, <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  store <8 x i64> %shuffle.i.i859.i, ptr addrspace(7) %add.ptr.ascast.i858.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i860.i = getelementptr inbounds nuw i8, ptr %246, i20 320
  %add.ptr.ascast.i861.i = addrspacecast ptr %add.ptr.i860.i to ptr addrspace(7)
  %shuffle4.i.i862.i = shufflevector <32 x i64> %247, <32 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <8 x i64> %shuffle4.i.i862.i, ptr addrspace(7) %add.ptr.ascast.i861.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i863.i = getelementptr inbounds nuw i8, ptr %246, i20 384
  %add.ptr.ascast.i864.i = addrspacecast ptr %add.ptr.i863.i to ptr addrspace(7)
  %shuffle9.i.i865.i = shufflevector <32 x i64> %247, <32 x i64> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  store <8 x i64> %shuffle9.i.i865.i, ptr addrspace(7) %add.ptr.ascast.i864.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i866.i = getelementptr inbounds nuw i8, ptr %246, i20 448
  %add.ptr.ascast.i867.i = addrspacecast ptr %add.ptr.i866.i to ptr addrspace(7)
  %shuffle10.i.i868.i = shufflevector <32 x i64> %247, <32 x i64> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  store <8 x i64> %shuffle10.i.i868.i, ptr addrspace(7) %add.ptr.ascast.i867.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i869.i = getelementptr inbounds nuw i8, ptr %246, i20 512
  %add.ptr.ascast.i870.i = addrspacecast ptr %add.ptr.i869.i to ptr addrspace(7)
  %inc214.i = add nuw i32 %j.01128.i, 1
  %exitcond1143.not.i = icmp eq i32 %inc214.i, %28
  br i1 %exitcond1143.not.i, label %for.cond.cleanup.i, label %for.body.i, !llvm.loop !50

for.body152.i:                                    ; preds = %for.body152.i, %for.body.i
  %fW.sroa.0.11115.i = phi <32 x i32> [ %fW.sroa.0.11102.i, %for.body.i ], [ %fW.sroa.0.1.i, %for.body152.i ]
  %fW.sroa.26.11114.i = phi i32 [ %fW.sroa.26.11101.i, %for.body.i ], [ %fW.sroa.26.1.i, %for.body152.i ]
  %fA.sroa.0.11113.i = phi <32 x i32> [ %fA.sroa.0.11100.i, %for.body.i ], [ %fA.sroa.0.1.i, %for.body152.i ]
  %fA.sroa.34.11112.i = phi i32 [ %fA.sroa.34.11099.i, %for.body.i ], [ %fA.sroa.34.1.i, %for.body152.i ]
  %pW.11111.i = phi ptr addrspace(6) [ %pW.11098.i, %for.body.i ], [ %pW.1.i, %for.body152.i ]
  %pA.11110.i = phi ptr addrspace(5) [ %pA.11097.i, %for.body.i ], [ %pA.1.i, %for.body152.i ]
  %accum_0.1.in1109.i = phi <64 x i32> [ %220, %for.body.i ], [ %290, %for.body152.i ]
  %accum_1.1.in1108.i = phi <64 x i32> [ %221, %for.body.i ], [ %291, %for.body152.i ]
  %accum_2.1.in1107.i = phi <64 x i32> [ %222, %for.body.i ], [ %292, %for.body152.i ]
  %accum_3.1.in1106.i = phi <64 x i32> [ %223, %for.body.i ], [ %293, %for.body152.i ]
  %i.01105.i = phi i32 [ 3, %for.body.i ], [ %inc.i, %for.body152.i ]
  %dimsAI.sroa.31.11104.i = phi i32 [ %204, %for.body.i ], [ %274, %for.body152.i ]
  %dimsAI.sroa.23.11103.i = phi i32 [ %202, %for.body.i ], [ %272, %for.body152.i ]
  %248 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %pA.11110.i, <32 x i32> %fA.sroa.0.11113.i, i32 %fA.sroa.34.11112.i)
  %249 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %248, 0
  %250 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %248, 1
  %251 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %248, 2
  %252 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) %249, <32 x i32> %250, i32 %251)
  %253 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %252, 0
  %254 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %252, 1
  %255 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %252, 2
  %256 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) %pW.11111.i, <32 x i32> %fW.sroa.0.11115.i, i32 %fW.sroa.26.11114.i)
  %257 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %256, 0
  %258 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %256, 1
  %259 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %256, 2
  %260 = tail call { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p5.p5(ptr addrspace(5) %253, <32 x i32> %254, i32 %255)
  %261 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %260, 0
  %262 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %260, 1
  %263 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %260, 2
  %264 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %260, 3
  %265 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %260, 4
  %266 = trunc nuw i32 %dimsAI.sroa.23.11103.i to i20
  %267 = trunc nuw i32 %dimsAI.sroa.31.11104.i to i20
  %268 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) %261, <32 x i32> %262, i32 %263, i20 %30, i20 %31, i20 %266, i20 %32, i20 %33, i20 %267, i20 %34)
  %269 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %268, 5
  %270 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %268, 6
  %271 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %268, 3
  %272 = zext i20 %271 to i32
  %273 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %268, 4
  %274 = zext i20 %273 to i32
  %275 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p6.p6(ptr addrspace(6) %257, <32 x i32> %258, i32 %259)
  %276 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %275, 0
  %277 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %275, 1
  %278 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %275, 2
  %279 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %275, 3
  %280 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %275, 4
  %281 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p6.p6(ptr addrspace(6) %276, <32 x i32> %277, i32 %278, i20 0)
  %282 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %281, 3
  %283 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %281, 4
  %284 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %264, <8 x i8> %265, <64 x i8> %269, <8 x i8> %270, i32 %35)
  %285 = extractvalue { <64 x i8>, <8 x i8> } %284, 0
  %286 = extractvalue { <64 x i8>, <8 x i8> } %284, 1
  %287 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %264, <8 x i8> %265, <64 x i8> %269, <8 x i8> %270, i32 %36)
  %288 = extractvalue { <64 x i8>, <8 x i8> } %287, 0
  %289 = extractvalue { <64 x i8>, <8 x i8> } %287, 1
  %290 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %285, <8 x i8> %286, <64 x i8> %279, <8 x i8> %280, <64 x i32> %accum_0.1.in1109.i, i32 780)
  %291 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %288, <8 x i8> %289, <64 x i8> %279, <8 x i8> %280, <64 x i32> %accum_1.1.in1108.i, i32 780)
  %292 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %285, <8 x i8> %286, <64 x i8> %282, <8 x i8> %283, <64 x i32> %accum_2.1.in1107.i, i32 780)
  %293 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %288, <8 x i8> %289, <64 x i8> %282, <8 x i8> %283, <64 x i32> %accum_3.1.in1106.i, i32 780)
  %inc.i = add nuw nsw i32 %i.01105.i, 1
  %pA.1.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %268, 0
  %pW.1.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %281, 0
  %fA.sroa.34.1.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %268, 2
  %fA.sroa.0.1.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %268, 1
  %fW.sroa.26.1.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %281, 2
  %fW.sroa.0.1.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %281, 1
  %exitcond.not.i = icmp eq i32 %inc.i, %37
  br i1 %exitcond.not.i, label %for.cond.cleanup151.i, label %for.body152.i, !llvm.loop !53

for.body224.i:                                    ; preds = %for.body224.i, %for.cond219.preheader.i
  %j218.01137.i = phi i32 [ 0, %for.cond219.preheader.i ], [ %inc310.i, %for.body224.i ]
  %p_sum_in_0.11136.i = phi ptr addrspace(5) [ %19, %for.cond219.preheader.i ], [ %add.ptr.ascast.i927.i, %for.body224.i ]
  %p_sum_in_1.11135.i = phi ptr addrspace(7) [ %20, %for.cond219.preheader.i ], [ %add.ptr.ascast.i959.i, %for.body224.i ]
  %p_out.0.in1134.i = phi ptr [ %ofm, %for.cond219.preheader.i ], [ %348, %for.body224.i ]
  %iterator_pout_cnt0.01133.i = phi i32 [ 0, %for.cond219.preheader.i ], [ %347, %for.body224.i ]
  %p_out.0.i = addrspacecast ptr %p_out.0.in1134.i to ptr addrspace(5)
  %294 = load <8 x i64>, ptr addrspace(5) %p_sum_in_0.11136.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %295 = addrspacecast ptr addrspace(5) %p_sum_in_0.11136.i to ptr
  %add.ptr.i898.i = getelementptr inbounds nuw i8, ptr %295, i20 64
  %add.ptr.ascast.i899.i = addrspacecast ptr %add.ptr.i898.i to ptr addrspace(5)
  %296 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i899.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i902.i = getelementptr inbounds nuw i8, ptr %295, i20 128
  %add.ptr.ascast.i903.i = addrspacecast ptr %add.ptr.i902.i to ptr addrspace(5)
  %297 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i903.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i906.i = getelementptr inbounds nuw i8, ptr %295, i20 192
  %add.ptr.ascast.i907.i = addrspacecast ptr %add.ptr.i906.i to ptr addrspace(5)
  %298 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i907.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle12.i.i909.i = shufflevector <8 x i64> %297, <8 x i64> %298, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i910.i = getelementptr inbounds nuw i8, ptr %295, i20 256
  %add.ptr.ascast.i911.i = addrspacecast ptr %add.ptr.i910.i to ptr addrspace(5)
  %299 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i911.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i914.i = getelementptr inbounds nuw i8, ptr %295, i20 320
  %add.ptr.ascast.i915.i = addrspacecast ptr %add.ptr.i914.i to ptr addrspace(5)
  %300 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i915.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i918.i = getelementptr inbounds nuw i8, ptr %295, i20 384
  %add.ptr.ascast.i919.i = addrspacecast ptr %add.ptr.i918.i to ptr addrspace(5)
  %301 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i919.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %add.ptr.i922.i = getelementptr inbounds nuw i8, ptr %295, i20 448
  %add.ptr.ascast.i923.i = addrspacecast ptr %add.ptr.i922.i to ptr addrspace(5)
  %302 = load <8 x i64>, ptr addrspace(5) %add.ptr.ascast.i923.i, align 64, !tbaa !4, !alias.scope !26, !noalias !47
  %shuffle12.i.i925.i = shufflevector <8 x i64> %301, <8 x i64> %302, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i926.i = getelementptr inbounds nuw i8, ptr %295, i20 512
  %add.ptr.ascast.i927.i = addrspacecast ptr %add.ptr.i926.i to ptr addrspace(5)
  %303 = load <8 x i64>, ptr addrspace(7) %p_sum_in_1.11135.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %304 = addrspacecast ptr addrspace(7) %p_sum_in_1.11135.i to ptr
  %add.ptr.i930.i = getelementptr inbounds nuw i8, ptr %304, i20 64
  %add.ptr.ascast.i931.i = addrspacecast ptr %add.ptr.i930.i to ptr addrspace(7)
  %305 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i931.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i934.i = getelementptr inbounds nuw i8, ptr %304, i20 128
  %add.ptr.ascast.i935.i = addrspacecast ptr %add.ptr.i934.i to ptr addrspace(7)
  %306 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i935.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i938.i = getelementptr inbounds nuw i8, ptr %304, i20 192
  %add.ptr.ascast.i939.i = addrspacecast ptr %add.ptr.i938.i to ptr addrspace(7)
  %307 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i939.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle12.i.i941.i = shufflevector <8 x i64> %306, <8 x i64> %307, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i942.i = getelementptr inbounds nuw i8, ptr %304, i20 256
  %add.ptr.ascast.i943.i = addrspacecast ptr %add.ptr.i942.i to ptr addrspace(7)
  %308 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i943.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i946.i = getelementptr inbounds nuw i8, ptr %304, i20 320
  %add.ptr.ascast.i947.i = addrspacecast ptr %add.ptr.i946.i to ptr addrspace(7)
  %309 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i947.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i950.i = getelementptr inbounds nuw i8, ptr %304, i20 384
  %add.ptr.ascast.i951.i = addrspacecast ptr %add.ptr.i950.i to ptr addrspace(7)
  %310 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i951.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %add.ptr.i954.i = getelementptr inbounds nuw i8, ptr %304, i20 448
  %add.ptr.ascast.i955.i = addrspacecast ptr %add.ptr.i954.i to ptr addrspace(7)
  %311 = load <8 x i64>, ptr addrspace(7) %add.ptr.ascast.i955.i, align 64, !tbaa !4, !alias.scope !28, !noalias !48
  %shuffle12.i.i957.i = shufflevector <8 x i64> %310, <8 x i64> %311, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i958.i = getelementptr inbounds nuw i8, ptr %304, i20 512
  %add.ptr.ascast.i959.i = addrspacecast ptr %add.ptr.i958.i to ptr addrspace(7)
  %add.ptr.i961.i = getelementptr inbounds i8, ptr %p_out.0.in1134.i, i20 %idx.ext.i960.i
  %add.ptr.ascast.i962.i = addrspacecast ptr %add.ptr.i961.i to ptr addrspace(5)
  %shuffle.i.i963.i = shufflevector <8 x i64> %299, <8 x i64> %300, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %312 = bitcast <16 x i64> %shuffle.i.i963.i to <32 x float>
  %313 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %312)
  %314 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %313, <32 x bfloat> %splat.splat.i.i)
  %315 = extractvalue { <32 x bfloat>, i32 } %314, 0
  store <32 x bfloat> %315, ptr addrspace(5) %add.ptr.ascast.i962.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %add.ptr.i965.i = getelementptr inbounds i8, ptr %p_out.0.in1134.i, i20 %idx.ext.i964.i
  %add.ptr.ascast.i966.i = addrspacecast ptr %add.ptr.i965.i to ptr addrspace(5)
  %shuffle1.i.i967.i = shufflevector <32 x i64> %shuffle12.i.i925.i, <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %316 = bitcast <16 x i64> %shuffle1.i.i967.i to <32 x float>
  %317 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %316)
  %318 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %317, <32 x bfloat> %splat.splat.i.i)
  %319 = extractvalue { <32 x bfloat>, i32 } %318, 0
  store <32 x bfloat> %319, ptr addrspace(5) %add.ptr.ascast.i966.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %shuffle.i.i968.i = shufflevector <8 x i64> %294, <8 x i64> %296, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %320 = bitcast <16 x i64> %shuffle.i.i968.i to <32 x float>
  %321 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %320)
  %322 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %321, <32 x bfloat> %splat.splat.i.i)
  %323 = extractvalue { <32 x bfloat>, i32 } %322, 0
  store <32 x bfloat> %323, ptr addrspace(5) %p_out.0.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %add.ptr.i969.i = getelementptr inbounds nuw i8, ptr %p_out.0.in1134.i, i20 64
  %add.ptr.ascast.i970.i = addrspacecast ptr %add.ptr.i969.i to ptr addrspace(5)
  %shuffle1.i.i971.i = shufflevector <32 x i64> %shuffle12.i.i909.i, <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %324 = bitcast <16 x i64> %shuffle1.i.i971.i to <32 x float>
  %325 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %324)
  %326 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %325, <32 x bfloat> %splat.splat.i.i)
  %327 = extractvalue { <32 x bfloat>, i32 } %326, 0
  store <32 x bfloat> %327, ptr addrspace(5) %add.ptr.ascast.i970.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %add.ptr.i973.i = getelementptr inbounds i8, ptr %p_out.0.in1134.i, i20 %idx.ext.i972.i
  %add.ptr.ascast.i974.i = addrspacecast ptr %add.ptr.i973.i to ptr addrspace(5)
  %add.ptr.i976.i = getelementptr inbounds i8, ptr %add.ptr.i973.i, i20 %idx.ext.i960.i
  %add.ptr.ascast.i977.i = addrspacecast ptr %add.ptr.i976.i to ptr addrspace(5)
  %shuffle.i.i978.i = shufflevector <8 x i64> %308, <8 x i64> %309, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %328 = bitcast <16 x i64> %shuffle.i.i978.i to <32 x float>
  %329 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %328)
  %330 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %329, <32 x bfloat> %splat.splat.i.i)
  %331 = extractvalue { <32 x bfloat>, i32 } %330, 0
  store <32 x bfloat> %331, ptr addrspace(5) %add.ptr.ascast.i977.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %add.ptr.i980.i = getelementptr inbounds i8, ptr %add.ptr.i973.i, i20 %idx.ext.i964.i
  %add.ptr.ascast.i981.i = addrspacecast ptr %add.ptr.i980.i to ptr addrspace(5)
  %shuffle1.i.i982.i = shufflevector <32 x i64> %shuffle12.i.i957.i, <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %332 = bitcast <16 x i64> %shuffle1.i.i982.i to <32 x float>
  %333 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %332)
  %334 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %333, <32 x bfloat> %splat.splat.i.i)
  %335 = extractvalue { <32 x bfloat>, i32 } %334, 0
  store <32 x bfloat> %335, ptr addrspace(5) %add.ptr.ascast.i981.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %shuffle.i.i983.i = shufflevector <8 x i64> %303, <8 x i64> %305, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %336 = bitcast <16 x i64> %shuffle.i.i983.i to <32 x float>
  %337 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %336)
  %338 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %337, <32 x bfloat> %splat.splat.i.i)
  %339 = extractvalue { <32 x bfloat>, i32 } %338, 0
  store <32 x bfloat> %339, ptr addrspace(5) %add.ptr.ascast.i974.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %add.ptr.i984.i = getelementptr inbounds nuw i8, ptr %add.ptr.i973.i, i20 64
  %add.ptr.ascast.i985.i = addrspacecast ptr %add.ptr.i984.i to ptr addrspace(5)
  %shuffle1.i.i986.i = shufflevector <32 x i64> %shuffle12.i.i941.i, <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %340 = bitcast <16 x i64> %shuffle1.i.i986.i to <32 x float>
  %341 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %340)
  %342 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %341, <32 x bfloat> %splat.splat.i.i)
  %343 = extractvalue { <32 x bfloat>, i32 } %342, 0
  store <32 x bfloat> %343, ptr addrspace(5) %add.ptr.ascast.i985.i, align 64, !tbaa !4, !alias.scope !30, !noalias !55
  %344 = trunc nuw i32 %iterator_pout_cnt0.01133.i to i20
  %345 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr %add.ptr.i980.i, i20 %49, i20 %50, i20 %51, i20 %344)
  %346 = extractvalue { ptr, i20 } %345, 1
  %347 = zext i20 %346 to i32
  %348 = extractvalue { ptr, i20 } %345, 0
  %inc310.i = add nuw i32 %j218.01137.i, 1
  %exitcond1144.not.i = icmp eq i32 %inc310.i, %28
  br i1 %exitcond1144.not.i, label %_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t.exit, label %for.body224.i, !llvm.loop !56

_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t.exit: ; preds = %for.body224.i, %for.cond.cleanup.i
  ret void
}

; Function Attrs: mustprogress noinline
declare dso_local void @_Z21convert_bf16_to_bfp16I8bfloat16Lb0EEvPT_PS0_RK13BfToBfpParams(ptr, ptr noalias, ptr nonnull align 32 dereferenceable(32)) local_unnamed_addr #2

; Function Attrs: nounwind willreturn memory(none)
declare <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat>) #3

; Function Attrs: nounwind willreturn memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5), <32 x i32>, i32) #4

; Function Attrs: nounwind willreturn memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6), <32 x i32>, i32) #4

; Function Attrs: nounwind willreturn memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p5.p5(ptr addrspace(5), <32 x i32>, i32) #4

; Function Attrs: nounwind willreturn memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #4

; Function Attrs: nounwind willreturn memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p6.p6(ptr addrspace(6), <32 x i32>, i32) #4

; Function Attrs: nounwind willreturn memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p6.p6(ptr addrspace(6), <32 x i32>, i32, i20) #4

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, i32) #5

; Function Attrs: nounwind willreturn memory(inaccessiblemem: read)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, <64 x i32>, i32) #6

; Function Attrs: nounwind willreturn memory(inaccessiblemem: read)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, i32) #6

; Function Attrs: nounwind willreturn memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat>, <32 x bfloat>) #5

; Function Attrs: nounwind willreturn memory(inaccessiblemem: read)
declare <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float>) #6

; Function Attrs: nounwind willreturn memory(none)
declare { ptr, i20 } @llvm.aie2p.add.2d(ptr, i20, i20, i20, i20) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare void @llvm.assume(i1 noundef) #7

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)
declare void @llvm.experimental.noalias.scope.decl(metadata) #8

attributes #0 = { nounwind willreturn memory(inaccessiblemem: write) }
attributes #1 = { mustprogress "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #2 = { mustprogress noinline "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #3 = { nounwind willreturn memory(none) }
attributes #4 = { nounwind willreturn memory(argmem: read) }
attributes #5 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #6 = { nounwind willreturn memory(inaccessiblemem: read) }
attributes #7 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #8 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite) }
attributes #9 = { "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 20.0.0git (/scratch/work/clang c9c710446ecbf2938aa5fc31019abd6827e2335a)"}
!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{!8, !5, i64 11}
!8 = !{!"_ZTS18conv2d_bf16_params", !5, i64 0, !5, i64 1, !9, i64 2, !9, i64 4, !5, i64 6, !5, i64 7, !5, i64 8, !5, i64 9, !5, i64 10, !5, i64 11, !10, i64 12, !5, i64 14, !5, i64 15, !5, i64 16, !5, i64 17, !9, i64 18, !9, i64 20, !9, i64 22, !11, i64 64}
!9 = !{!"short", !5, i64 0}
!10 = !{!"__bf16", !5, i64 0}
!11 = !{!"_ZTS27conv2d_bf16_internal_params", !12, i64 0, !12, i64 4, !5, i64 8, !5, i64 9, !12, i64 12, !12, i64 16, !12, i64 20, !5, i64 24, !5, i64 28, !5, i64 32, !5, i64 33, !12, i64 36, !5, i64 40, !5, i64 41, !12, i64 44, !12, i64 48, !12, i64 52, !12, i64 56, !12, i64 60, !12, i64 64, !12, i64 68, !12, i64 72, !12, i64 76, !12, i64 80, !12, i64 84, !12, i64 88, !12, i64 92, !12, i64 96, !12, i64 100, !12, i64 104, !12, i64 108, !12, i64 112, !12, i64 116, !12, i64 120, !12, i64 124, !12, i64 128, !12, i64 132, !12, i64 136, !12, i64 140, !12, i64 144, !12, i64 148, !12, i64 152, !12, i64 156, !12, i64 160, !12, i64 164, !12, i64 168, !12, i64 172, !12, i64 176, !12, i64 180, !5, i64 184, !5, i64 185, !12, i64 188, !12, i64 192, !9, i64 196, !12, i64 200, !13, i64 204, !13, i64 232, !13, i64 260, !5, i64 288}
!12 = !{!"int", !5, i64 0}
!13 = !{!"_ZTS9dims_3d_t", !12, i64 0, !12, i64 4, !12, i64 8, !12, i64 12, !12, i64 16, !12, i64 20, !12, i64 24}
!14 = !{!8, !5, i64 96}
!15 = !{!8, !12, i64 76}
!16 = !{!8, !5, i64 8}
!17 = !{!8, !5, i64 16}
!18 = !{!8, !12, i64 80}
!19 = !{!8, !5, i64 104}
!20 = !{!8, !12, i64 116}
!21 = !{!8, !12, i64 84}
!22 = !{!8, !12, i64 120}
!23 = !{!24}
!24 = distinct !{!24, !25, !"_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t: %weights"}
!25 = distinct !{!25, !"_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t"}
!26 = !{!27}
!27 = distinct !{!27, !25, !"_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t: %psum_0"}
!28 = !{!29}
!29 = distinct !{!29, !25, !"_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t: %psum_1"}
!30 = !{!31}
!31 = distinct !{!31, !25, !"_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t: %output"}
!32 = !{!8, !12, i64 64}
!33 = !{!34, !24, !27, !29, !31}
!34 = distinct !{!34, !25, !"_Z14conv2d_genericILh1EL5act_t0E8bfloat16EvPS1_S2_PfS3_S2_R18conv2d_bf16_params10out_mode_t: %input"}
!35 = !{!8, !9, i64 260}
!36 = !{!24, !27, !29, !31}
!37 = !{!12, !12, i64 0}
!38 = !{!8, !12, i64 200}
!39 = !{!8, !12, i64 204}
!40 = !{!8, !12, i64 196}
!41 = !{!8, !12, i64 256}
!42 = !{!8, !12, i64 192}
!43 = !{!8, !12, i64 112}
!44 = !{!8, !12, i64 236}
!45 = !{!8, !12, i64 240}
!46 = !{!8, !12, i64 108}
!47 = !{!34, !24, !29, !31}
!48 = !{!34, !24, !27, !31}
!49 = !{!34, !27, !29, !31}
!50 = distinct !{!50, !51, !52}
!51 = !{!"llvm.loop.mustprogress"}
!52 = !{!"llvm.loop.itercount.range", i64 2}
!53 = distinct !{!53, !51, !54}
!54 = !{!"llvm.loop.itercount.range", i64 5}
!55 = !{!34, !24, !27, !29}
!56 = distinct !{!56, !51, !52}
